const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';

const FETCH_EXPENSES_REQUEST = 'FETCH_EXPENSES_REQUEST';
const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS';
const FETCH_EXPENSES_FAILURE = 'FETCH_EXPENSES_FAILURE';

const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST';
const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
const CREATE_EXPENSE_FAILURE = 'CREATE_EXPENSE_FAILURE';

const DELETE_EXPENSE_REQUEST = 'DELETE_EXPENSE_REQUEST';
const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';
const DELETE_EXPENSE_FAILURE = 'DELETE_EXPENSE_FAILURE';

export default {
  FETCH_EXPENSES_REQUEST,
  FETCH_EXPENSES_SUCCESS,
  FETCH_EXPENSES_FAILURE,
  CREATE_EXPENSE_REQUEST,
  CREATE_EXPENSE_SUCCESS,
  CREATE_EXPENSE_FAILURE,
  DELETE_EXPENSE_REQUEST,
  DELETE_EXPENSE_SUCCESS,
  DELETE_EXPENSE_FAILURE,
  SHOW_MODAL,
  HIDE_MODAL,
};
