const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';

const SET_FILTER = 'SET_FILTER';

const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST';
const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
const CREATE_EXPENSE_FAILURE = 'CREATE_EXPENSE_FAILURE';

const FETCH_EXPENSES_REQUEST = 'FETCH_EXPENSES_REQUEST';
const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS';
const FETCH_EXPENSES_FAILURE = 'FETCH_EXPENSES_FAILURE';

const UPDATE_EXPENSE_REQUEST = 'UPDATE_EXPENSE_REQUEST';
const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS';
const UPDATE_EXPENSE_FAILURE = 'UPDATE_EXPENSE_FAILURE';

const DELETE_EXPENSE_REQUEST = 'DELETE_EXPENSE_REQUEST';
const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';
const DELETE_EXPENSE_FAILURE = 'DELETE_EXPENSE_FAILURE';

const FETCH_ALL_EXPENSES_REQUEST = 'FETCH_ALL_EXPENSES_REQUEST';
const FETCH_ALL_EXPENSES_SUCCESS = 'FETCH_ALL_EXPENSES_SUCCESS';
const FETCH_ALL_EXPENSES_FAILURE = 'FETCH_ALL_EXPENSES_FAILURE';

export default {
  FETCH_EXPENSES_REQUEST,
  FETCH_EXPENSES_SUCCESS,
  FETCH_EXPENSES_FAILURE,
  CREATE_EXPENSE_REQUEST,
  CREATE_EXPENSE_SUCCESS,
  CREATE_EXPENSE_FAILURE,
  UPDATE_EXPENSE_REQUEST,
  UPDATE_EXPENSE_SUCCESS,
  UPDATE_EXPENSE_FAILURE,
  DELETE_EXPENSE_REQUEST,
  DELETE_EXPENSE_SUCCESS,
  DELETE_EXPENSE_FAILURE,
  FETCH_ALL_EXPENSES_REQUEST,
  FETCH_ALL_EXPENSES_SUCCESS,
  FETCH_ALL_EXPENSES_FAILURE,
  SHOW_MODAL,
  HIDE_MODAL,
  SET_FILTER,
};
