const SHOW_MODAL = 'toptal/users/SHOW_MODAL';
const HIDE_MODAL = 'toptal/users/HIDE_MODAL';

const CREATE_USER_REQUEST = 'toptal/users/CREATE_USER_REQUEST';
const CREATE_USER_SUCCESS = 'toptal/users/CREATE_USER_SUCCESS';
const CREATE_USER_FAILURE = 'toptal/users/CREATE_USER_FAILURE';

const FETCH_USERS_REQUEST = 'toptal/users/FETCH_USERS_REQUEST';
const FETCH_USERS_SUCCESS = 'toptal/users/FETCH_USERS_SUCCESS';
const FETCH_USERS_FAILURE = 'toptal/users/FETCH_USERS_FAILURE';

const UPDATE_USER_REQUEST = 'toptal/users/UPDATE_USER_REQUEST';
const UPDATE_USER_SUCCESS = 'toptal/users/UPDATE_USER_SUCCESS';
const UPDATE_USER_FAILURE = 'toptal/users/UPDATE_USER_FAILURE';

const DELETE_USER_REQUEST = 'toptal/users/DELETE_USER_REQUEST';
const DELETE_USER_SUCCESS = 'toptal/users/DELETE_USER_SUCCESS';
const DELETE_USER_FAILURE = 'toptal/users/DELETE_USER_FAILURE';

export default {
  FETCH_USERS_REQUEST,
  FETCH_USERS_SUCCESS,
  FETCH_USERS_FAILURE,
  CREATE_USER_REQUEST,
  CREATE_USER_SUCCESS,
  CREATE_USER_FAILURE,
  UPDATE_USER_REQUEST,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_FAILURE,
  DELETE_USER_REQUEST,
  DELETE_USER_SUCCESS,
  DELETE_USER_FAILURE,
  SHOW_MODAL,
  HIDE_MODAL,
};
