const FETCH_ALL_USERS_REQUEST = 'FETCH_ALL_USERS_REQUEST';
const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
const FETCH_ALL_USERS_FAILURE = 'FETCH_ALL_USERS_FAILURE';

export default {
  FETCH_ALL_USERS_REQUEST,
  FETCH_ALL_USERS_SUCCESS,
  FETCH_ALL_USERS_FAILURE,
};
