const LOGIN_REQUEST = 'toptal/auth/LOGIN_REQUEST';
const LOGIN_SUCCESS = 'toptal/auth/LOGIN_SUCCESS';
const LOGIN_FAILURE = 'toptal/auth/LOGIN_FAILURE';

const REGISTER_REQUEST = 'toptal/auth/REGISTER_REQUEST';
const REGISTER_SUCCESS = 'toptal/auth/REGISTER_SUCCESS';
const REGISTER_FAILURE = 'toptal/auth/REGISTER_FAILURE';

const LOGOUT = 'toptal/auth/LOGOUT';

export default {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  LOGOUT,
};
